name: Deploy Backend to AWS S3

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies and zip Lambda functions
        run: |
          mkdir -p dist
          for dir in backend/*/; do
            function_name=$(basename "$dir")
            echo "Processing $function_name"
            cd "$dir"

            # Install dependencies if package.json exists
            if [ -f "package.json" ]; then
              npm install
            fi

            # Zip the function folder
            zip -r "../../dist/${function_name}.zip" .

            cd - # Go back to root directory
          done
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Deploy Lambda Functions
        run: |
          for file in dist/*.zip; do
            function_name=$(basename "$file" .zip)
            echo "Deploying $function_name"
            
            # Use deploy-lambda for cleaner deployment
            aws lambda update-function-code \
              --function-name "$function_name" \
              --zip-file "fileb://$file"
          done
        shell: bash