name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Delete existing gh-pages branch
        run: git branch -D gh-pages || true
      
      - name: Create new gh-pages branch
        run: git checkout -b gh-pages
      
      - name: Install dependencies and build
        run: |
          cd frontend
          npm install
          npm run build
        shell: bash
      
      - name: Remove unnecessary files
        run: |
          shopt -s extglob
          cd frontend
          mv dist/* ../
          cd ..
          rm -rf frontend
        shell: bash
      
      - name: Add CNAME file
        run: echo "chrispecmusic.com" > CNAME
      
      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Deploy"
          git push --force origin gh-pages