name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Delete existing gh-pages branch
        run: git branch -D gh-pages-test || true
      
      - name: Create new gh-pages branch
        run: git checkout -b gh-pages-test
      
      - name: Install dependencies and build
        run: |
          npm install
          npm run build
      
      - name: Remove unnecessary files
        run: |
          rm -r !("dist"|"CNAME")
          mv dist/* .
          rm -r dist
      
      - name: Add CNAME file
        run: echo "chrispecmusic.com" > CNAME
      
      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Deploy"
          git push origin gh-pages-test
