name: Deploy Backend to AWS S3

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install backend dependencies
        run: |
          cd backend
          npm install
        shell: bash

      - name: Zip backend directory
        run: |
          cd backend
          zip -r ../backend.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Sync backend directory to S3
        run: aws s3 cp ./backend.zip s3://chrispecmusic-backend/backend.zip